### ISSUE TITLE
Setup Deployment

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#261]
## EPIC
Il completamento di questo epic comporterà una valutazione di fattibilità e la creazione di una serie di issue per la lavorazione dell'attività in oggetto.

## Dettagli
Al momento il deployment è riproducibile senza problemi, ma andrebbe forse Dockerizzato (ricordo che Iacopo suggeriva docker compose) o Kubernetizzato. Da discutere con Luca e Iacopo per trovare soluzioni sicure, _"one-click"_ o quasi.

Questa la lista che ci eravamo appuntati

- [x] Rendere completamente configurabili tramite env vars i parametri relativi ai servizi usati #271 
- [x] Entry Redis #271 
- [x] Entry Postgres #271 
- [x] Entry ES #271 
- [x] Entry Celery #271 
- [x] Entry HTTP #271 
- [x] Entry RTD #271 
- [x] Entry storage (per lo storage delle build) #271 
- [ ] Setup ambiente kubernetes dev #280
- [ ] Setup ambiente kubernetes live #281

# Storie / PR Collegate

- #271 
- #273 
- #274 
- #275 
- #276 
- #277 
- #279

**Comment by yakky** [comment]
Come discusso con Luca l'obiettivo sarebbe kubernetizzare tutto partendo dall'ambiente dev

Possiamo partire dai Dockerfile di RTD e poi creare un repository analogo a quelli già esistenti nell'organizzazione teamdigitale per il deploy kubernetes seguendo le linee guida di quanto già sviluppato
