### ISSUE TITLE
Ricerca e tassonomia documenti

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#363]
## EPIC
Questo EPIC è solo un raccoglitore delle attività necessarie al completamento della nuova ricerca, coerentemente con quanto definito nel documento di progetto:

https://docs.google.com/presentation/d/1_oV7oU9cE6t013iUg6PdMbQeQ214hTTd2wJMiCLb4-4/edit?usp=sharing 

## Dettagli

Le issue collegate a questa attività vanno gestite attraverso PR su branch dedicato [`363-ricerca`](https://github.com/italia/docs.italia.it/tree/feature/363-ricerca), e sono:
- [x] https://github.com/italia/docs.italia.it/issues/256
- [x] https://github.com/italia/docs.italia.it/issues/255
- [x] https://github.com/italia/docs.italia.it/issues/252
- [x] https://github.com/italia/docs.italia.it/issues/259 (da discutere la fattibilità)
- [x] https://github.com/italia/docs.italia.it/issues/206
- [x] https://github.com/italia/docs.italia.it/issues/235 (potrebbe essere già sistemata)
- [x] https://github.com/italia/docs.italia.it/issues/314

**Comment by yakky** [comment]
@francescozaia questa si può chiudere, giusto? al netto del debug, le feature sono tutte implementatre
